# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagetest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 470)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 681, 341))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("images/Slider1.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.cloud = QtWidgets.QPushButton(self.centralwidget)
        self.cloud.setGeometry(QtCore.QRect(0, 340, 321, 25))
        self.cloud.setObjectName("cloud")
        self.me = QtWidgets.QPushButton(self.centralwidget)
        self.me.setGeometry(QtCore.QRect(318, 340, 331, 25))
        self.me.setObjectName("me")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.cloud.clicked.connect(self.show_cloud)
        self.me.clicked.connect(self.show_me)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cloud.setText(_translate("MainWindow", "cloud"))
        self.me.setText(_translate("MainWindow", "me"))

    def show_cloud(self):
        self.photo.setPixmap(QtGui.QPixmap("images/Slider1.jpg"))
        
    def show_me(self):
        self.photo.setPixmap(QtGui.QPixmap("images/Slider2.jpg"))
        
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
